### ISSUE TITLE
Don't send the message

### ISSUE THREAD

**Issue by DolceJ0Lly** [PhoenixCreation/whatsapp-spammer#2]
Give me on console this:
"Hello from spammer..." sent -> 1 times
VM845:52 "Hello from spammer..." sent -> 2 times
VM845:52 "Hello from spammer..." sent -> 3 times
VM845:52 "Hello from spammer..." sent -> 4 times
VM845:52 "Hello from spammer..." sent -> 5 times
VM845:52 "Hello from spammer..." sent -> 6 times
VM845:52 "Hello from spammer..." sent -> 7 times
VM845:52 "Hello from spammer..." sent -> 8 times
VM845:52 "Hello from spammer..." sent -> 9 times
VM845:52 "Hello from spammer..." sent -> 10 times
But on my phone no messages and on my screen (web.whathsapp.com) no message

anyone can _**help me?**_

**Comment by PhoenixCreation** [comment]
Hi, I am sorry for late response but I have been busy in other projects.

I checked with the latest version of whatsapp web and I found that they have changed the implementation from their end. So this script will not work in there.

Technical details:
- I don't remember if they were using react using or not back in the days  built this script. But they are using it now.
- Whatsapp web changed their code to start using the react hot keys and authentic event filtering.
- This allows it to block almost all scripts running from the console.
- So it is very tricky to get it work through console.

Workarounds:
- There are none to use directly from the developer console.
- You can use automation tools such as selenium with python or java to automate this process. [Not recommended, As it has higher chances of getting caught by whatsapp]

# I am leaving this issue open for other coming to this repo.

**Comment by PhoenixCreation** [comment]
Hi @DolceJ0Lly, Sorry for late response. I have updated the script to be working again on Edge and Chrome. Although firefox is still having issues. Closing this issue as it is fixed. Feel free to reopen it if issue persists or create a new issue.
